variable "aws_region" {}
variable "vpc_id" {}
variable "key_name" {}
variable "my_ip" {}
variable "dns_zone" {}
variable "env_name" {}
variable "pub_sub_a" {}
variable "pub_sub_b" {}
variable "priv_sub_a" {}
variable "priv_sub_b" {}
variable "pub_sub_a_cidr" {}
variable "pub_sub_b_cidr" {}
variable "ssl_arn" {}
variable "srv_size" {}
variable "hst_size" {}
variable "hst_max" {}
variable "hst_min" {}
variable "hst_des" {}
variable "reg_token" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_class" {}
variable "db_storage" {}
variable "db_backup_retention" {}
variable "db_multi_az" {}
variable "db_final_snapshot" {}
variable "rancher_admin_name" {}
variable "rancher_admin_username" {}
variable "rancher_admin_password" {}
variable "ami_type" {
  type = "map"
  default = {
    eu-west-1    = "ami-64b2a802"
    eu-west-2    = "ami-4806102c"
    eu-central-1 = "ami-8c52f4e3"
  }
}
